apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-customisations
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: console-customisations/resources
    repoURL: 'https://github.com/evanshortiss/rht-summit-2023-gitops-cluster-mgmt'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
