apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-namespaces
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: namespaces/resources/overlays
    repoURL: 'https://github.com/evanshortiss/rht-summit-2023-gitops-cluster-mgmt'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
